on: 
  push :
    branches: [main]

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name : step1
        run: echo ${{ secrets.SECRET_TEST }}

      - name : list_elements
        run: ls -a -l

      - name : Console
        run: echo "Done"