on: workflow_dispatch

jobs: 
  job1:
    runs-on: ubuntu-latest
    steps:
      - name : step1
        run: echo ${{ secrets.SECRET_TEST }}

      - name : list_elements
        run: ls -a -l

      - name: Checkout code
        uses: actions/checkout@v6

      - name : Console
        run: echo "Done"